### ISSUE TITLE
Delete deleted refs

### ISSUE THREAD

**Issue by mlocati** [concrete5/core_splitter#2]
Let's assume that:
- in day 1 the [main repo](https://github.com/concrete5/concrete5/) contains the branches `A` and `B`:  
  the `splitcore` script correctly pushes those 2 branches to the [final repo](https://github.com/concrete5/concrete5-core).
- in day 2 the main repo contains the branches `A`, and `C`:
  the `splitcore` script correctly pushes those 2 branches to the final repo, but it doesn't delete the remote branch `B` which doesn't exist anymore in the main repo.

For instance, we currently have the `release/8.4.0` branch in the [splitted repo](https://github.com/concrete5/concrete5-core/tree/release/8.4.0) but [not in the main repo](https://github.com/concrete5/concrete5/tree/release/8.4.0).

This can be solved in 2 ways:
1. we never delete branches in the main repo. But @aembler prefers to work directly on the main repo...
2. the `splitcore` deletes the refs that exists in the splitted repo but not in the original repo

**Comment by KorvinSzanto** [comment]
I think #2 is the way we should do this. Today I just try to prune them every so often, we should just automate that and make pruning a part of deploy.
